<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');

?>
<header class="main-header">

	<?php echo $userBar; ?>

	<div class="main-header__top-bar container">
	<?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => NULL], true), ['class' => 'advanced-search']); ?>	
		<div class="main-header__search-form">
			<?php echo $this->partial('common/search-form'); ?>
		</div>
	</div>
	<hr class="alignfull">

	<div class="main-header__main-bar container">
		<div class="main-header__site-title">
			<a href="<?php echo $site->url(); ?>">
			<?php if ($this->themeSetting('logo')): ?>
				<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $this->escapeHtml( $site->title() ); ?>" />
			<?php else: ?>
				<?php echo $this->escapeHtml( $site->title() ); ?>
			<?php endif; ?>
			</a>
		</div>

		<nav class="main-navigation">
			<div class="main-navigation__container">
				<?php
				echo $site->publicNav()->menu()->renderMenu(null, [
					'addClassToListItem' => true,
					'maxDepth' => $this->themeSetting('nav_depth') - 1
				]);
				?>
			</div>
			<div class="main-navigation__toggle">
				<span></span>
				<span></span>
				<span></span>
			</div>
		</nav>
	</div>

</header>
